name = "minecraft-mod"
author = "Fletcher C."
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f3695f96fa380a975417c6677659ccb78f86b976b752e4a3c1e33bd788b1b0b7"

[versions]
minecraft = "26.3"
fabric = "0.19.5"
